using Kst.Api.Dtos;
using Kst.Application.LongTermShortages;
using Kst.Domain.Common;
using Kst.Domain.LongTermShortages;
using Kst.Exports.Contracts;
namespace Kst.Api.Endpoints;

public static class LongTermShortagesEndpoints
{
    public static void MapLongTermShortagesEndpoints(this IEndpointRouteBuilder app) => app.MapGet("/api/v1/workspaces/{assignmentId:guid}/long-term-shortages", Get).WithName("GetLongTermShortages").WithTags("LongTermShortages").Produces<LongTermShortagesResponseDto>().ProducesProblem(400).ProducesProblem(404).ProducesProblem(409).ProducesProblem(503);
    public static void MapLongTermShortagesExportEndpoints(this IEndpointRouteBuilder app) => app.MapPost("/api/v1/workspaces/{assignmentId:guid}/long-term-shortages/export", Export).WithName("ExportLongTermShortages").WithTags("LongTermShortages").Produces(StatusCodes.Status200OK).ProducesProblem(400).ProducesProblem(404).ProducesProblem(409).ProducesProblem(503);
    private static async Task<IResult> Get(Guid assignmentId, string? snapshotId, LongTermShortagesService service, CancellationToken ct, bool includeManufacturedParts = false, bool includePhantoms = false) { if (!Guid.TryParse(snapshotId, out var id)) return Results.ValidationProblem(new Dictionary<string, string[]> { { "snapshotId", ["snapshotId is required and must be a valid GUID."] } }); try { var r = await service.GetAsync(assignmentId, new SnapshotId(id), new LongTermShortagePopulationOptions(includeManufacturedParts, includePhantoms), ct); return r.Kind switch { LongTermShortagesOutcomeKind.Loaded => Results.Ok(new LongTermShortagesResponseDto(r.SnapshotId!.Value.ToString(), r.RefreshDate!.Value, r.IsStale, r.Warning, r.Rows!.Select(Map).ToList())), LongTermShortagesOutcomeKind.MpsNotLoaded => Results.Problem("MPS data has not been loaded.", statusCode: 409), LongTermShortagesOutcomeKind.SnapshotChanged => Results.Problem("Snapshot changed.", statusCode: 409), _ => Results.Problem("Long-Term Shortages unavailable.", statusCode: 503) }; } catch (LongTermShortagesWorkspaceNotFoundException) { return Results.NotFound(); } }
    private static LongTermShortageRowDto Map(LongTermShortageRow r) => new(r.ComponentPart, r.UnitOfMeasure, r.QadStatus, r.Description, r.IsKss, r.LeadTimeWeeks, r.Planner, r.OpeningQoh, LongTermShortageQuantityDisplayPolicy.Round(r.OpeningQoh, r.UnitOfMeasure), r.SafetyStockState.ToString(), r.SafetyStock, r.SafetyStock is null ? null : LongTermShortageQuantityDisplayPolicy.Round(r.SafetyStock.Value, r.UnitOfMeasure), r.Severity.ToString(), r.FirstSafetyStockShortWeek, r.FirstCriticalShortWeek, r.DemandParentParts, r.OtherProgramParentParts, r.Weeks.Select(w => new LongTermShortageWeekDto(w.WeekNumber, w.WeekStart, w.WorkOrderDemand, LongTermShortageQuantityDisplayPolicy.Round(w.WorkOrderDemand, r.UnitOfMeasure), w.ForecastDemand, LongTermShortageQuantityDisplayPolicy.Round(w.ForecastDemand, r.UnitOfMeasure), LongTermShortageQuantityDisplayPolicy.Round(w.WorkOrderDemand + w.ForecastDemand, r.UnitOfMeasure), w.PurchaseOrderSupply, LongTermShortageQuantityDisplayPolicy.Round(w.PurchaseOrderSupply, r.UnitOfMeasure), w.Balance, LongTermShortageQuantityDisplayPolicy.Round(w.Balance, r.UnitOfMeasure), w.Severity.ToString())).ToList(), r.PurchaseOrders.Select(po => new LongTermPurchaseOrderDto(po.PoNumber, po.PoLine, po.DueDate, po.OpenQuantity, LongTermShortageQuantityDisplayPolicy.Round(po.OpenQuantity, r.UnitOfMeasure), po.Confirmed, po.ManufacturerItem, po.IsScheduled)).ToList(), r.BuyerPlannerCode);
    private static async Task<IResult> Export(Guid assignmentId, ExportLongTermShortagesRequestDto request, LongTermShortagesService service, IExportService exports) { if (!Guid.TryParse(request.SnapshotId, out var id) || request.ComponentParts is null) return Results.ValidationProblem(new Dictionary<string, string[]> { { "snapshotId", ["snapshotId is required and must be a valid GUID."] } }); try { var result = await service.GetCachedForExportAsync(assignmentId, new SnapshotId(id), request.ComponentParts, new LongTermShortagePopulationOptions(request.IncludeManufacturedParts, request.IncludePhantoms)); if (result.Kind != LongTermShortagesOutcomeKind.Loaded) return Results.Problem(statusCode: result.Kind is LongTermShortagesOutcomeKind.MpsNotLoaded or LongTermShortagesOutcomeKind.SnapshotChanged ? 409 : 503); var name = NormalizeFileName(result.WorkspaceName); var bytes = exports.CreateLongTermShortagesWorkbook(name, result.RefreshDate!.Value, result.Rows!); return Results.File(bytes, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", $"{name}-Shortages-{result.RefreshDate:yyyy-MM-dd}.xlsx"); } catch (LongTermShortagesWorkspaceNotFoundException) { return Results.NotFound(); } }
    private static string NormalizeFileName(string? workspaceName) { var normalized = System.Text.RegularExpressions.Regex.Replace(workspaceName ?? "workspace", "[^A-Za-z0-9]+", "-").Trim('-'); return string.IsNullOrEmpty(normalized) ? "workspace" : normalized; }
}
