<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Kst.Domain\Kst.Domain.csproj" />
    <ProjectReference Include="..\..\Kst.Application\Kst.Application.csproj" />
    <ProjectReference Include="..\..\Kst.Infrastructure\Kst.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Kst.Integrations.Qad\Kst.Integrations.Qad.csproj" />
    <ProjectReference Include="..\..\Kst.Integrations.Shortages\Kst.Integrations.Shortages.csproj" />
    <ProjectReference Include="..\..\Kst.Exports\Kst.Exports.csproj" />
    <ProjectReference Include="..\..\Kst.Api\Kst.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>